export class Search {
  searchId: number;
  customersId: number;
  unitOwnersId: number | null;
  propertyCondition: number | null;
  furniture: number | null;
  dateSearch: Date;
  evacuationDate: Date | null;
  publishDate: Date | null;
  address: string;
  description: string;
  fromFloor: number | null;
  toFloor: number | null;
  fromArea: number | null;
  toArea: number | null;
  minRoomsNum: number | null;
  maxRoomsNum: number | null;
  minPrice: number | null;
  maxPrice: number | null;
  viewsNum: number | null;
  relevant: boolean | null;
  parking: boolean | null;
  pandorDoors: boolean | null;
  solarHeater: boolean | null;
  airConditioning: boolean | null;
  accessForDisabled: boolean | null;
  animal: boolean | null;
  securityRoom: boolean | null;
  elevator: boolean | null;
  terrace: boolean | null;
  floorsBuilding: number | null;
  propertyTax: number | null;
  committeeHome: number | null;
  payment: number | null;
  flexible: boolean | null;
  partners: boolean | null;
  warehouse: boolean | null;
  longTerm: boolean | null;
  kosherKitchen: boolean | null;
  bars: boolean | null;
  save: boolean;
  lat: number | null;
  lng: number | null;

  // export class Search {
  // SearchId: Number | null;
  // CustomersId: Number | null;
  // UnitOwnersId: Number | null;
  // PropertyCondition: Number | null;
  // Furniture: Number | null;
  // DateSearch: Date | null;
  // EvacuationDate: Date | null;
  // PublishDate: Date | null;
  // Address: string | null;
  // Description: string | null;
  // Number?: Number | null;
  // FromFloor?: Number | null;
  // ToFloor?: Number | null;
  // FromArea?: Number | null;
  // ToArea?: Number | null;
  // MinRoomsNum: Number | null;
  // MaxRoomsNum: Number | null;
  // MinPrice: Number | null;
  // MaxPrice: Number | null;
  // ViewsNum: Number | null;
  // Relevant: Boolean | null;
  // Parking: Boolean | null;
  // PandorDoors: Boolean | null;
  // SolarHeater: Boolean | null;
  // AirConditioning: Boolean | null;
  // AccessForDisabled: Boolean | null;
  // Animal: Boolean | null;
  // SecurityRoom: Boolean | null;
  // Elevator: Boolean | null;
  // Terrace: Boolean | null;
  // floorsBuilding: number | null;
  // propertyTax: number | null;
  // committeeHome: number | null;
  // payment: number | null;
  // flexible: boolean | null;
  // partners: boolean | null;
  // warehouse: boolean | null;
  // longTerm: boolean | null;
  // kosherKitchen: boolean | null;
  // bars: boolean | null;
  // lat: number | null;
  // lng: number | null;

  constructor() {
    this.searchId = 0;
    this.customersId = 1;
    // this.UnitOwnersId = 0;
    // this.PropertyCondition = 0;
    // this.Furniture = 0;
    this.dateSearch = new Date();
    // this.EvacuationDate = new Date();
    // this.PublishDate = new Date();
    // this.City = '';
    // this.Neighborhood = '';
    // this.Street = '';
    // this.Description = '';
    // this.Number = 0;
    // this.FromFloor = 0;
    // this.ToFloor = 0;
    // this.FromArea = 0;
    // this.ToArea = 0;
    // this.MinRoomsNum = 0;
    // this.MaxRoomsNum = 0;
    // this.MinPrice = 0;
    // this.MaxPrice = 0;
    // this.ViewsNum = 0;
    // this.Relevant = false;
    // this.Parking = false;
    // this.PandorDoors = false;
    // this.SolarHeater = false;
    // this.AirConditioning = false;
    // this.AccessForDisabled = false;
    // this.Animal = false;
    // this.SecurityRoom = false;
    // this.Elevator = false;
    // this.Terrace = false;
  }
}
